### ISSUE TITLE
Decimal handling is inccorect

### ISSUE THREAD

**Issue by raullenchai** [mimoprotocol/mimo-contract#6]
<img width="417" alt="Screen Shot 2020-11-01 at 8 19 00 AM" src="https://user-images.githubusercontent.com/989846/97808293-f03a1d80-1c1a-11eb-8c6b-008e7eead44b.png">

This is a testing token minted using minttoken.io which has 1212 in total and does not have 18 decimals and the display here is not right

**Comment by j2-jonjohn** [comment]
wrong repo
